<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
	    <RootNamespace></RootNamespace>
        <OutputType>Exe</OutputType>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
    <ItemGroup>
        <None Update="Texts\InlinePictures.rtf">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <Content Include="Pictures\ReadersChoice.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <EmbeddedResource Include="Resources\information.png">
          <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="DevExpress.Document.Processor" Version="24.2.*" />
	    <PackageReference Include="DevExpress.RichEdit.Core" Version="24.2.*" />
    </ItemGroup>
</Project>